alias heget='ssh heget'
alias hegetx='ssh -XC heget'
#alias kekcc="auto_login.sh 'kekcc' 'takaesu' 'hE12517@1422'"
alias kekcc='ssh heget-kekcc'
alias kekccx="auto_loginx.sh 'kekcc' 'takaesu' 'hE12517@1422'"
alias ucl='ssh ucl'
alias ucl-ingrid='ssh ucl-ingrid'
alias ingrid='ssh ingrid'
alias sakura='ssh sakura'
alias ec2='ssh -i ~/.ssh/use1.pem ec2-user@ec2-54-65-54-101.ap-northeast-1.compute.amazonaws.com'
 
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias ss='cd $STUDY;ls'
alias phys='cd $PHYSLIB;ls'
alias lib='cd $LIB;ls'
alias pac='cd $PACKAGES;ls'
alias pacd='cd $PACKAGES_D;ls'
alias eve='cd $EVENTS;ls'
alias sh='cd $PACKAGES/sh;ls'
alias pro='cd $PROJECTS;ls'
alias prod='cd $PROJECTS_D;ls'
alias gey='cd $MG_ME_PY;ls'
alias talk='cd $STUDY_D/my_talks;ls'
alias ctalk='cd $STUDY_D/my_talks/13.09.30_KEKPH@KEK;ls'
alias prod='cd $PROJECTS_D;ls'

alias cfmc='cd $PROJECTS/cfmc;ls'
alias cfmcd='cd $PROJECTS_D/cfmc;ls'
alias t2kk='cd $PROJECTS/T2KK/beam_neu_v1.1;ls'
alias fit='cd $PROJECTS/T2KK/nuance_data/Snare_hbk;ls'
alias w4j2='cd $PROJECTS/w4j2/LHEAnalysis_v1;ls'
alias atdm='cd $PROJECTS/atdm;ls'

alias rmrf='rm -rf'
alias cprf='cp -rf'
alias mv='mv -f'
alias m='make'
alias mc='make clean'
alias ch='./check'
alias mch='make;./check'
alias sb='source $HOME/Dropbox/.bashrc'
alias ali='e $HOME/Dropbox/.bash_aliases'
#alias eali='ali_pull; ali'
#alias ali_push='ul.sh $HOME/.bash_aliases sak'
#alias ali_pull='dl_old.sh .bash_aliases sak; mv -f .bash_aliases $HOME/.'
alias ebash='e $HOME/Dropbox/.bashrc'
alias chm='chmod +x'
alias em="e Makefile"

alias sa='./bin/standalone'
alias new='./bin/newprocess'
alias g='./bin/generate_events'
alias proc='e Cards/proc_card_mg5.dat'
alias par='e Cards/param_card.dat'
alias run='e Cards/run_card.dat'
alias py='e Cards/pythia_card.dat'
alias mf='e matrix.f'
alias cf='e check_sa.f'

alias bi='bzr init;bzr add .;bzr commit -m "initialized"'
alias ba='bzr add'
alias bs='bzr status'
alias bcc='bzr commit --strict -m'
alias bl='bzr log --forward'
alias br='bzr rm'
alias big='bzr ignore'
alias buc'=bzr uncommit'
alias bnc'=bc "nc";rpush'

alias giti='touch README.md;git init;git add .;git commit -m "initialized"'
alias gita='git add'
alias gitc='git commit -m'
alias gitb='git branch'
alias gitch='git checkout'
alias gitlogo='git log --oneline'

alias rpull='rsync_pull.sh'
alias rpush='rsync_push.sh'
alias rcheck='rsync_check.sh'
alias rrm='rsync_rm.sh'

#alias mg5='$MG5/bin/mg5'
alias mg5='$MG5/bin/mg5_aMC'
alias ma5='$MA5/bin/ma5'
alias nco='$PROJECTS/cfmg/MG5_nco/bin/mg5'
alias nco_conf='e $PROJECTS/cfmg/MG5_nco/input/mg5_configuration.txt'
alias mam='$PACKAGES/MadAnalysis/plot_events'
alias tdm='$PACKAGES/td_linux/td'
alias enw='emacs -nw'
alias e='emacs -nw'
alias lhe2root='$PACKAGES/ExRootAnalysis/ExRootLHEFConverter'
alias root='root -l'
alias op='open -a Preview'